version: '2'
services:
    php-apache-dev:
        image: 'webdevops/php-apache-dev:8.1'
        links:
            - 'mysql:mysql'
        volumes:
            - './:/app'
        ports:
            - '81:80'
        depends_on:
            - mysql
        environment:
            - PHP_DISPLAY_ERRORS=1
            - extension
            - WEB_DOCUMENT_ROOT=/app/public
    mysql:
        image: 'mysql:8.3.0'
        environment:
            MYSQL_ROOT_PASSWORD: 'toor'
            MYSQL_DATABASE: 'laravel'
        volumes:
            - './.docker/mysql:/var/lib/mysql'
        ports:
            - '3307:3306'
